swagger: "2.0"
info:
  version: "1.0.0"
  title: Shoe Order API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /users:
    x-swagger-router-controller: user_controller
    get:
      tags: ["users"]
      summary: Returns all created users with the basic informations
      operationId: getAll
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/GetUsersListResponse"

    post:
      tags: ["users"]
      summary: Create a new user
      operationId: create
      parameters:
        - name: username
          description: Can be anything you want
          in: formData
          required: true
          type: string
        - name: password
          description: At least 8 chars
          in: formData
          required: true
          type: string
        - name: firstname
          description: Firstame of the new user
          in: formData
          required: true
          type: string
        - name: lastname
          description: Lastname of the new user
          in: formData
          required: true
          type: string
        - name: email
          description: Email of the new user
          in: formData
          required: true
          type: string
        - name: birthdate
          description: Birthdate of the new user
          in: formData
          required: true
          type: string
        - name: country
          description: Country of the new user
          in: formData
          required: true
          type: string
        - name: state
          description: State of the new user
          in: formData
          required: true
          type: string
        - name: phone
          description: Phone of the new user
          in: formData
          required: true
          type: string
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/PostUserResponse"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/PostUserBadRquestError"

  /users/{userId}:
    x-swagger-router-controller: user_controller
    get:
      tags: ["users"]
      summary: Get a user by his ID
      description: Returns a user by his ID with all basic informations
      operationId: getUserById
      parameters:
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/GetUserResponse"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/Error"
    put:
      tags: ["users"]
      summary: Modify all properties of a user
      operationId: fullEdit
      parameters:
        - name: userId
          description: Id of the user to update
          type: string
          in: path
          required: true
        - name: username
          description: Username of the user to update
          in: formData
          required: true
          type: string
        - name: password
          description: Password of the user to update
          in: formData
          required: true
          type: string
        - name: firstname
          description: Firstame of the user to update
          in: formData
          required: true
          type: string
        - name: lastname
          description: Lastname of the user to update
          in: formData
          required: true
          type: string
        - name: email
          description: Email of the user to update
          in: formData
          required: true
          type: string
        - name: birthdate
          description: Birthdate of the user to update
          in: formData
          required: true
          type: string
        - name: country
          description: Country of the user to update
          in: formData
          required: true
          type: string
        - name: state
          description: State of the user to update
          in: formData
          required: true
          type: string
        - name: phone
          description: Phone of the user to update
          in: formData
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/FullEditUserResponse"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/FullEditUserByIdNotFound"
    patch:
      tags: ["users"]
      summary: Modify some properties of a user
      operationId: partialEdit
      parameters:
        - name: userId
          description: Id of the user to update
          type: string
          in: path
          required: true
        - name: username
          description: Username of the user to update
          in: formData
          required: false
          type: string
        - name: password
          description: Password of the user to update
          in: formData
          required: false
          type: string
        - name: firstname
          description: Firstame of the user to update
          in: formData
          required: false
          type: string
        - name: lastname
          description: Lastname of the user to update
          in: formData
          required: false
          type: string
        - name: email
          description: Email of the user to update
          in: formData
          required: false
          type: string
        - name: birthdate
          description: Birthdate of the user to update
          in: formData
          required: false
          type: string
        - name: country
          description: Country of the user to update
          in: formData
          required: false
          type: string
        - name: state
          description: State of the user to update
          in: formData
          required: false
          type: string
        - name: phone
          description: Phone of the user to update
          in: formData
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/PartialEditUserResponse"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/PartialEditUserByIdNotFound"
    delete:
      tags: ["users"]
      summary: Delete a specific user with his Id
      description: Will delete all informations about a specific user
      operationId: remove
      parameters:
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DeleteUserByIdSuccessOrError"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/DeleteUserByIdSuccessOrError"

  /login:
    x-swagger-router-controller: login_controller
    post:
      tags: ["login"]
      summary: Return the loggedIn response
      operationId: login
      parameters:
        - name: username
          description: the username of the user who want to be logged
          in: formData
          required: true
          type: string
        - name: password
          description: the password of the user who want to be logged
          in: formData
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/LoginResponse"
        400:
          description: Bad Request
          schema:
            required:
              - code
              - loggedIn
              - message
            properties:
              code:
                type: number
              loggedIn:
                type: boolean
              message:
                type: string

# complex objects have schema definitions
definitions:

  Error:
    type: object
    properties:
      code:
        type: number
      message:
        type: string
    required:
      - code
      - message

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  LoginResponse:
    required:
      - code
      - loggedIn
      - message
    properties:
      code:
        type: number
      loggedIn:
        type: boolean
      message:
        type: string

  GetUsersListResponse:
    required:
      - users
    properties:
      users:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            firstname:
              type: string
            lastname:
              type: string
            email:
              type: string
            birthdate:
              type: string
            country:
              type: string
            state:
              type: string
            phone:
              type: string
            created_at:
              type: string
            updated_at:
              type: string

  GetUserResponse:
    required:
      - user
    properties:
      user:
        type: object
        properties:
          id:
            type: integer
          firstname:
            type: string
          lastname:
            type: string
          email:
            type: string
          birthdate:
            type: string
          country:
            type: string
          state:
            type: string
          phone:
            type: string
          created_at:
            type: string
          updated_at:
            type: string

  PostUserResponse:
    required:
      - code
      - user
    properties:
      code:
        type: number
      user:
        type: object
        properties:
          id:
            type: integer
          firstname:
            type: string
          lastname:
            type: string
          email:
            type: string
          birthdate:
            type: string
          country:
            type: string
          state:
            type: string
          phone:
            type: string
          created_at:
            type: string
          updated_at:
            type: string

  PostUserBadRquestError:
    required:
      - code
      - type
    type: object
    properties:
      code:
        type: number
      type:
        type: string
      messages:
        type: array
        items:
          type: string
      fields:
        type: array
        items:
          type: string

  FullEditUserResponse:
    required:
      - code
      - message
      - user
    type: object
    properties:
      code:
        type: number
      message:
        type: string
      user:
        type: object
        properties:
          id:
            type: integer
          firstname:
            type: string
          lastname:
            type: string
          email:
            type: string
          birthdate:
            type: string
          country:
            type: string
          state:
            type: string
          phone:
            type: string
          created_at:
            type: string
          updated_at:
            type: string

  PartialEditUserResponse:
    required:
      - code
      - message
      - user
    type: object
    properties:
      code:
        type: number
      message:
        type: string
      user:
        type: object
        properties:
          id:
            type: integer
          firstname:
            type: string
          lastname:
            type: string
          email:
            type: string
          birthdate:
            type: string
          country:
            type: string
          state:
            type: string
          phone:
            type: string
          created_at:
            type: string
          updated_at:
            type: string

  FullEditUserByIdNotFound:
    required:
      - code
      - message
    type: object
    properties:
      code:
        type: number
      message:
        type: string

  PartialEditUserByIdNotFound:
    required:
      - code
      - message
    type: object
    properties:
      code:
        type: number
      message:
        type: string

  DeleteUserByIdSuccessOrError:
    required:
      - code
      - message
    type: object
    properties:
      code:
        type: number
      message:
        type: string
